#!/bin/sh
#PBS -S /bin/sh
#PBS -A alauring_fluxm
#PBS -N run_IBV_all
#PBS -q fluxm
#PBS -M avalesan@umich.edu
#PBS -m abe
#PBS -j oe
#PBS -V
#PBS -l nodes=1:ppn=2,mem=280gb,walltime=72:00:00

echo Running job name $PBS_JOBNAME with ID $PBS_JOBID on host $PBS_O_HOST;
echo Working directory is $PBS_O_WORKDIR
echo Start time: `date`;


cd $PBS_O_WORKDIR

python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/aligning_pipeline.groovy "../Run_2445/data/fastq_forVIC/*fastq" ../Run_2445/data/aligned_output_VIC ../Run_2445/options_VIC.yaml # Alignment stage
python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/aligning_pipeline.groovy "../Run_2446/data/fastq_forVIC/*fastq" ../Run_2446/data/aligned_output_VIC ../Run_2446/options_VIC.yaml	# Alignment stage
python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/deepsnv_pipeline.groovy "../Run_2445/data/aligned_output_VIC/removed_duplicates/*.bam" ../Run_2445/data/deepSNV_pipeline_VIC/ ../Run_2445/options_VIC_2445.yaml # deepSNV stage
python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/deepsnv_pipeline.groovy "../Run_2446/data/aligned_output_VIC/removed_duplicates/*.bam" ../Run_2446/data/deepSNV_pipeline_VIC/ ../Run_2446/options_VIC_2446.yaml # deepSNV stage

python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/aligning_pipeline.groovy "../Run_2445/data/fastq_forYAM/*fastq" ../Run_2445/data/aligned_output_YAM ../Run_2445/options_YAM.yaml # Alignment stage
python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/aligning_pipeline.groovy "../Run_2446/data/fastq_forYAM/*fastq" ../Run_2446/data/aligned_output_YAM ../Run_2446/options_YAM.yaml   # Alignment stage
python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/deepsnv_pipeline.groovy "../Run_2445/data/aligned_output_YAM/removed_duplicates/*.bam" ../Run_2445/data/deepSNV_pipeline_YAM/ ../Run_2445/options_YAM_2445.yaml # deepSNV sta$
python ~/variant_pipeline/bin/variantPipeline.py ~/variant_pipeline/scripts/deepsnv_pipeline.groovy "../Run_2446/data/aligned_output_YAM/removed_duplicates/*.bam" ../Run_2446/data/deepSNV_pipeline_YAM/ ../Run_2446/options_YAM_2446.yaml # deepSNV stage

echo Finish time: `date`
